function [cameraParams] = calibrator()

% Auto-generated by cameraCalibrator app on 29-Nov-2019
%-------------------------------------------------------


% Define images to process
imageFileNames = {'pic/IMG_20191126_164817.jpg',...
    'pic/IMG_20191126_164820.jpg',...
    'pic/IMG_20191126_164823.jpg',...
    'pic/IMG_20191126_164830.jpg',...
    'pic/IMG_20191126_164833.jpg',...
    'pic/IMG_20191126_164836.jpg',...
    'pic/IMG_20191126_164839.jpg',...
    'pic/IMG_20191126_164841.jpg',...
    'pic/IMG_20191126_164843.jpg',...
    'pic/IMG_20191126_164847.jpg',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 20;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
% h1=figure; showReprojectionErrors(cameraParams);
% 
% % Visualize pattern locations
% h2=figure; showExtrinsics(cameraParams, 'CameraCentric');
% 
% % Display parameter estimation errors
% displayErrors(estimationErrors, cameraParams);
% 
% % For example, you can use the calibration data to remove effects of lens distortion.
% undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')


